"""add edinet_profit_and_loss table.

Revision ID: 020f5df7040c
Revises: 086c83420b27
Create Date: 2026-02-11 09:09:26.082014

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "020f5df7040c"
down_revision: Union[str, Sequence[str], None] = "086c83420b27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to be idempotent ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table("edinet_profit_and_loss"):
        op.create_table(
            "edinet_profit_and_loss",
            sa.Column("doc_id", sa.String(length=50), nullable=False),
            sa.Column("sec_code", sa.String(length=10), nullable=False),
            sa.Column("filer_name", sa.String(length=255), nullable=True),
            sa.Column("submission_date", sa.Date(), nullable=False),
            sa.Column("period_end_date", sa.Date(), nullable=False),
            sa.Column("fiscal_year", sa.Integer(), nullable=True),
            sa.Column("report_type", sa.String(length=20), nullable=False),
            sa.Column(
                "operating_profit",
                sa.Numeric(precision=20, scale=2),
                nullable=True,
                comment="営業活動によるキャッシュフロー（百万円）",
            ),
            sa.Column(
                "eps",
                sa.Numeric(precision=20, scale=2),
                nullable=True,
                comment="1株当たり当期純利益（円）",
            ),
            sa.Column("candidate_contexts", sa.String(length=50), nullable=True),
            sa.Column("candidate_keys", sa.String(length=50), nullable=True),
            sa.Column("is_consolidated", sa.Boolean(), nullable=True),
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("sec_code", "period_end_date", name="uq_edinet_pl_sec_period"),
        )

        with op.batch_alter_table("edinet_profit_and_loss", schema=None) as batch_op:
            batch_op.create_index("idx_edinet_pl_doc_id", ["doc_id"], unique=False)
            batch_op.create_index("idx_edinet_pl_period_end", ["period_end_date"], unique=False)
            batch_op.create_index("idx_edinet_pl_sec_code", ["sec_code"], unique=False)
            batch_op.create_index(
                "idx_edinet_pl_sec_period", ["sec_code", "period_end_date"], unique=False
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted to be safe when table absent ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("edinet_profit_and_loss"):
        with op.batch_alter_table("edinet_profit_and_loss", schema=None) as batch_op:
            # drop indexes if they exist; batch_alter_table will ignore missing indexes
            try:
                batch_op.drop_index("idx_edinet_pl_sec_period")
            except Exception:
                pass
            try:
                batch_op.drop_index("idx_edinet_pl_sec_code")
            except Exception:
                pass
            try:
                batch_op.drop_index("idx_edinet_pl_period_end")
            except Exception:
                pass
            try:
                batch_op.drop_index("idx_edinet_pl_doc_id")
            except Exception:
                pass

        op.drop_table("edinet_profit_and_loss")

    # ### end Alembic commands ###
