"""add nikkei225_1d table

Revision ID: 0d155fb7e046
Revises: 21d928840c54
Create Date: 2026-03-26 12:10:39.198780

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d155fb7e046"
down_revision: Union[str, Sequence[str], None] = "21d928840c54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nikkei225_1d",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("timestamp", name="uix_nikkei225_1d_timestamp"),
    )
    with op.batch_alter_table("nikkei225_1d", schema=None) as batch_op:
        batch_op.create_index("idx_nikkei225_1d_timestamp", ["timestamp"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nikkei225_1d", schema=None) as batch_op:
        batch_op.drop_index("idx_nikkei225_1d_timestamp")

    op.drop_table("nikkei225_1d")
    # ### end Alembic commands ###
