"""add stock_master_updates handling

Revision ID: 0d5d2098df45
Revises: 5eb81fa2fa7a
Create Date: 2026-01-17 19:09:56.857379

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0d5d2098df45"
down_revision: Union[str, Sequence[str], None] = "5eb81fa2fa7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
