"""add relative_strength table

Revision ID: 21d928840c54
Revises: 8c6b6b094d99
Create Date: 2026-03-21 19:08:38.945329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d928840c54'
down_revision: Union[str, Sequence[str], None] = '8c6b6b094d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relative_strength',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('change_63days', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('change_126days', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('change_189days', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('change_252days', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('relative_strength_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock_master.stock_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'calculation_date', name='uq_relative_strength_symbol_date')
    )
    with op.batch_alter_table('relative_strength', schema=None) as batch_op:
        batch_op.create_index('idx_relative_strength_calculation_date', ['calculation_date'], unique=False)
        batch_op.create_index('idx_relative_strength_symbol', ['symbol'], unique=False)

    with op.batch_alter_table('edinet_document', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_edinet_doc_id', ['doc_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edinet_document', schema=None) as batch_op:
        batch_op.drop_constraint('uq_edinet_doc_id', type_='unique')

    with op.batch_alter_table('relative_strength', schema=None) as batch_op:
        batch_op.drop_index('idx_relative_strength_symbol')
        batch_op.drop_index('idx_relative_strength_calculation_date')

    op.drop_table('relative_strength')
    # ### end Alembic commands ###
