"""refactor: change dividend_yield_monitoring and screening_results to use symbol instead of sec_code

Revision ID: 46e4c7c13389
Revises: 021efaad97b1
Create Date: 2026-02-26 18:47:02.659612

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46e4c7c13389"
down_revision: Union[str, Sequence[str], None] = "021efaad97b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old indices on dividend_yield_monitoring
    with op.batch_alter_table("dividend_yield_monitoring", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_dividend_yield_monitoring_date"))
        batch_op.drop_index(batch_op.f("idx_dividend_yield_monitoring_purchase_level"))
        batch_op.drop_index(batch_op.f("idx_dividend_yield_monitoring_yield"))
        # Rename sec_code column to symbol
        batch_op.alter_column("sec_code", new_column_name="symbol")
        # Update unique constraint
        batch_op.drop_constraint("uq_dividend_yield_monitoring", type_="unique")
        batch_op.create_unique_constraint(
            "uq_dividend_yield_monitoring", ["symbol", "monitoring_date"]
        )
        # Recreate indices
        batch_op.create_index(
            "idx_dividend_yield_monitoring_date", ["monitoring_date"], unique=False
        )
        batch_op.create_index(
            "idx_dividend_yield_monitoring_purchase_level", ["purchase_level"], unique=False
        )
        batch_op.create_index(
            "idx_dividend_yield_monitoring_yield", ["dividend_yield"], unique=False
        )

    # Update screening_results table
    with op.batch_alter_table("screening_results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("symbol", sa.String(length=10), nullable=True))

    # Migrate data from sec_code to symbol for screening_results
    op.execute("UPDATE screening_results SET symbol = sec_code WHERE symbol IS NULL")

    # Make symbol NOT NULL after data migration
    with op.batch_alter_table("screening_results", schema=None) as batch_op:
        batch_op.alter_column("symbol", nullable=False)
        batch_op.drop_index(batch_op.f("idx_screening_results_sec_code"))
        batch_op.drop_constraint(batch_op.f("uq_screening_results_sec_eval"), type_="unique")
        batch_op.create_index("idx_screening_results_symbol", ["symbol"], unique=False)
        batch_op.create_unique_constraint(
            "uq_screening_results_symbol_eval", ["symbol", "evaluation_date"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert screening_results table changes
    with op.batch_alter_table("screening_results", schema=None) as batch_op:
        batch_op.drop_constraint("uq_screening_results_symbol_eval", type_="unique")
        batch_op.drop_index("idx_screening_results_symbol")
        batch_op.create_unique_constraint(
            batch_op.f("uq_screening_results_sec_eval"), ["sec_code", "evaluation_date"]
        )
        batch_op.create_index(
            batch_op.f("idx_screening_results_sec_code"), ["sec_code"], unique=False
        )
        batch_op.drop_column("symbol")

    # Revert dividend_yield_monitoring table changes
    with op.batch_alter_table("dividend_yield_monitoring", schema=None) as batch_op:
        batch_op.drop_index("idx_dividend_yield_monitoring_yield")
        batch_op.drop_index("idx_dividend_yield_monitoring_purchase_level")
        batch_op.drop_index("idx_dividend_yield_monitoring_date")
        batch_op.drop_constraint("uq_dividend_yield_monitoring", type_="unique")
        batch_op.alter_column("symbol", new_column_name="sec_code")
        batch_op.create_unique_constraint(
            "uq_dividend_yield_monitoring", ["sec_code", "monitoring_date"]
        )
        batch_op.create_index(
            batch_op.f("idx_dividend_yield_monitoring_date"), ["monitoring_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_dividend_yield_monitoring_purchase_level"),
            ["purchase_level"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_dividend_yield_monitoring_yield"), ["dividend_yield"], unique=False
        )

    # ### end Alembic commands ###
