"""Initial database schema.

Revision ID: 4e581533f2e4
Revises:
Create Date: 2026-01-13 21:49:21.701544

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e581533f2e4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_executions",
        sa.Column("batch_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_stocks", sa.Integer(), nullable=False),
        sa.Column("processed_stocks", sa.Integer(), nullable=False),
        sa.Column("successful_stocks", sa.Integer(), nullable=False),
        sa.Column("failed_stocks", sa.Integer(), nullable=False),
        sa.Column(
            "start_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_batch_executions_batch_type",
        "batch_executions",
        ["batch_type"],
        unique=False,
    )
    op.create_index(
        "idx_batch_executions_start_time",
        "batch_executions",
        ["start_time"],
        unique=False,
    )
    op.create_index(
        "idx_batch_executions_status",
        "batch_executions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "stock_master",
        sa.Column("stock_code", sa.String(length=10), nullable=False),
        sa.Column("stock_name", sa.String(length=100), nullable=False),
        sa.Column("market_category", sa.String(length=50), nullable=True),
        sa.Column("sector_code_33", sa.String(length=10), nullable=True),
        sa.Column("sector_name_33", sa.String(length=100), nullable=True),
        sa.Column("sector_code_17", sa.String(length=10), nullable=True),
        sa.Column("sector_name_17", sa.String(length=100), nullable=True),
        sa.Column("scale_code", sa.String(length=10), nullable=True),
        sa.Column("scale_category", sa.String(length=50), nullable=True),
        sa.Column("data_date", sa.String(length=8), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stock_code"),
    )
    op.create_index("idx_stock_master_active", "stock_master", ["is_active"], unique=False)
    op.create_index("idx_stock_master_code", "stock_master", ["stock_code"], unique=False)
    op.create_index(
        "idx_stock_master_market",
        "stock_master",
        ["market_category"],
        unique=False,
    )
    op.create_index(
        "idx_stock_master_sector_33",
        "stock_master",
        ["sector_code_33"],
        unique=False,
    )
    op.create_table(
        "stocks_15m",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_15m_symbol_timestamp"),
    )
    op.create_index("idx_stocks_15m_timestamp", "stocks_15m", ["timestamp"], unique=False)
    op.create_table(
        "stocks_1d",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1d_symbol_timestamp"),
    )
    op.create_index("idx_stocks_1d_timestamp", "stocks_1d", ["timestamp"], unique=False)
    op.create_table(
        "stocks_1h",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1h_symbol_timestamp"),
    )
    op.create_index("idx_stocks_1h_timestamp", "stocks_1h", ["timestamp"], unique=False)
    op.create_table(
        "stocks_1m",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1m_symbol_timestamp"),
    )
    op.create_index("idx_stocks_1m_timestamp", "stocks_1m", ["timestamp"], unique=False)
    op.create_table(
        "stocks_1mo",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1mo_symbol_timestamp"),
    )
    op.create_index("idx_stocks_1mo_timestamp", "stocks_1mo", ["timestamp"], unique=False)
    op.create_table(
        "stocks_1wk",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1wk_symbol_timestamp"),
    )
    op.create_index("idx_stocks_1wk_timestamp", "stocks_1wk", ["timestamp"], unique=False)
    op.create_table(
        "stocks_30m",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_30m_symbol_timestamp"),
    )
    op.create_index("idx_stocks_30m_timestamp", "stocks_30m", ["timestamp"], unique=False)
    op.create_table(
        "stocks_5m",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_5m_symbol_timestamp"),
    )
    op.create_index("idx_stocks_5m_timestamp", "stocks_5m", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_stocks_5m_timestamp", table_name="stocks_5m")
    op.drop_table("stocks_5m")
    op.drop_index("idx_stocks_30m_timestamp", table_name="stocks_30m")
    op.drop_table("stocks_30m")
    op.drop_index("idx_stocks_1wk_timestamp", table_name="stocks_1wk")
    op.drop_table("stocks_1wk")
    op.drop_index("idx_stocks_1mo_timestamp", table_name="stocks_1mo")
    op.drop_table("stocks_1mo")
    op.drop_index("idx_stocks_1m_timestamp", table_name="stocks_1m")
    op.drop_table("stocks_1m")
    op.drop_index("idx_stocks_1h_timestamp", table_name="stocks_1h")
    op.drop_table("stocks_1h")
    op.drop_index("idx_stocks_1d_timestamp", table_name="stocks_1d")
    op.drop_table("stocks_1d")
    op.drop_index("idx_stocks_15m_timestamp", table_name="stocks_15m")
    op.drop_table("stocks_15m")
    op.drop_index("idx_stock_master_sector_33", table_name="stock_master")
    op.drop_index("idx_stock_master_market", table_name="stock_master")
    op.drop_index("idx_stock_master_code", table_name="stock_master")
    op.drop_index("idx_stock_master_active", table_name="stock_master")
    op.drop_table("stock_master")
    op.drop_index("idx_batch_executions_status", table_name="batch_executions")
    op.drop_index("idx_batch_executions_start_time", table_name="batch_executions")
    op.drop_index("idx_batch_executions_batch_type", table_name="batch_executions")
    op.drop_table("batch_executions")
    # ### end Alembic commands ###
