"""Add EdinetDocument and normalize EDINET tables

Revision ID: 565383c201cb
Revises: 9e1f5a7c8d0a
Create Date: 2026-03-07 13:02:43.252493

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "565383c201cb"
down_revision: Union[str, Sequence[str], None] = "9e1f5a7c8d0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up any existing temporary tables from failed previous migrations (SQLite)
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_edinet_document")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_edinet_cash_flow_statement")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_edinet_profit_and_loss")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_edinet_stock_dividend")

    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists first
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS edinet_document (
            doc_id VARCHAR(50) NOT NULL,
            sec_code VARCHAR(10) NOT NULL,
            submission_date DATE NOT NULL,
            report_type VARCHAR(20) NOT NULL DEFAULT 'annual',
            candidate_contexts VARCHAR(50),
            candidate_keys VARCHAR(50),
            id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (doc_id)
        )
    """
    )

    with op.batch_alter_table("edinet_document", schema=None) as batch_op:
        batch_op.create_index("idx_edinet_doc_doc_id", ["doc_id"], unique=True, if_not_exists=True)
        batch_op.create_index(
            "idx_edinet_doc_sec_code", ["sec_code"], unique=False, if_not_exists=True
        )
        batch_op.create_index(
            "idx_edinet_doc_submission_date", ["submission_date"], unique=False, if_not_exists=True
        )

    with op.batch_alter_table("edinet_cash_flow_statement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("edinet_document_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("idx_edinet_cfs_doc_id"))
        batch_op.drop_index(batch_op.f("idx_edinet_cfs_sec_code"))
        batch_op.drop_index(batch_op.f("idx_edinet_cfs_sec_period"))
        batch_op.drop_constraint("uq_edinet_cfs_sec_period", type_="unique")
        batch_op.create_index("idx_edinet_cfs_document_id", ["edinet_document_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_edinet_cfs_doc_period", ["edinet_document_id", "period_end_date"]
        )
        batch_op.create_foreign_key(
            "fk_edinet_cfs_document_id", "edinet_document", ["edinet_document_id"], ["id"]
        )
        batch_op.drop_column("submission_date")
        batch_op.drop_column("sec_code")
        batch_op.drop_column("candidate_contexts")
        batch_op.drop_column("candidate_keys")
        batch_op.drop_column("report_type")
        batch_op.drop_column("doc_id")

    with op.batch_alter_table("edinet_profit_and_loss", schema=None) as batch_op:
        batch_op.add_column(sa.Column("edinet_document_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("idx_edinet_pl_doc_id"))
        batch_op.drop_index(batch_op.f("idx_edinet_pl_sec_code"))
        batch_op.drop_constraint("uq_edinet_pl_sec_period", type_="unique")
        batch_op.create_index("idx_edinet_pl_document_id", ["edinet_document_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_edinet_pl_doc_period", ["edinet_document_id", "period_end_date"]
        )
        batch_op.create_foreign_key(
            "fk_edinet_pl_document_id", "edinet_document", ["edinet_document_id"], ["id"]
        )
        batch_op.drop_column("submission_date")
        batch_op.drop_column("sec_code")
        batch_op.drop_column("candidate_contexts")
        batch_op.drop_column("candidate_keys")
        batch_op.drop_column("report_type")
        batch_op.drop_column("doc_id")

    with op.batch_alter_table("edinet_stock_dividend", schema=None) as batch_op:
        batch_op.add_column(sa.Column("edinet_document_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("idx_edinet_sd_doc_id"))
        batch_op.drop_index(batch_op.f("idx_edinet_sd_sec_code"))
        batch_op.drop_index(batch_op.f("idx_edinet_sd_sec_period"))
        batch_op.drop_constraint("uq_edinet_sd_sec_period", type_="unique")
        batch_op.create_index("idx_edinet_sd_document_id", ["edinet_document_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_edinet_sd_doc_period", ["edinet_document_id", "period_end_date"]
        )
        batch_op.create_foreign_key(
            "fk_edinet_sd_document_id", "edinet_document", ["edinet_document_id"], ["id"]
        )
        batch_op.drop_column("submission_date")
        batch_op.drop_column("sec_code")
        batch_op.drop_column("candidate_contexts")
        batch_op.drop_column("candidate_keys")
        batch_op.drop_column("report_type")
        batch_op.drop_column("doc_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("edinet_stock_dividend", schema=None) as batch_op:
        batch_op.add_column(sa.Column("doc_id", sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column("report_type", sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column("candidate_keys", sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column("candidate_contexts", sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column("sec_code", sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column("submission_date", sa.DATE(), nullable=False))
        batch_op.drop_constraint("fk_edinet_sd_document_id", type_="foreignkey")
        batch_op.drop_constraint("uq_edinet_sd_doc_period", type_="unique")
        batch_op.drop_index("idx_edinet_sd_document_id")
        batch_op.create_unique_constraint(
            batch_op.f("uq_edinet_sd_sec_period"), ["sec_code", "period_end_date"]
        )
        batch_op.create_index(
            batch_op.f("idx_edinet_sd_sec_period"), ["sec_code", "period_end_date"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_edinet_sd_sec_code"), ["sec_code"], unique=False)
        batch_op.create_index(batch_op.f("idx_edinet_sd_doc_id"), ["doc_id"], unique=False)
        batch_op.drop_column("edinet_document_id")

    with op.batch_alter_table("edinet_profit_and_loss", schema=None) as batch_op:
        batch_op.add_column(sa.Column("doc_id", sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(
            sa.Column(
                "report_type",
                sa.VARCHAR(length=20),
                server_default=sa.text("'annual'"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("candidate_keys", sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column("candidate_contexts", sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column("sec_code", sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column("submission_date", sa.DATE(), nullable=False))
        batch_op.drop_constraint("fk_edinet_pl_document_id", type_="foreignkey")
        batch_op.drop_constraint("uq_edinet_pl_doc_period", type_="unique")
        batch_op.drop_index("idx_edinet_pl_document_id")
        batch_op.create_unique_constraint(
            batch_op.f("uq_edinet_pl_sec_period"), ["sec_code", "period_end_date"]
        )
        batch_op.create_index(batch_op.f("idx_edinet_pl_sec_code"), ["sec_code"], unique=False)
        batch_op.create_index(batch_op.f("idx_edinet_pl_doc_id"), ["doc_id"], unique=False)
        batch_op.drop_column("edinet_document_id")

    with op.batch_alter_table("edinet_cash_flow_statement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("doc_id", sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column("report_type", sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column("candidate_keys", sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column("candidate_contexts", sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column("sec_code", sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column("submission_date", sa.DATE(), nullable=False))
        batch_op.drop_constraint("fk_edinet_cfs_document_id", type_="foreignkey")
        batch_op.drop_constraint("uq_edinet_cfs_doc_period", type_="unique")
        batch_op.drop_index("idx_edinet_cfs_document_id")
        batch_op.create_unique_constraint(
            batch_op.f("uq_edinet_cfs_sec_period"), ["sec_code", "period_end_date"]
        )
        batch_op.create_index(
            batch_op.f("idx_edinet_cfs_sec_period"), ["sec_code", "period_end_date"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_edinet_cfs_sec_code"), ["sec_code"], unique=False)
        batch_op.create_index(batch_op.f("idx_edinet_cfs_doc_id"), ["doc_id"], unique=False)
        batch_op.drop_column("edinet_document_id")

    with op.batch_alter_table("edinet_document", schema=None) as batch_op:
        batch_op.drop_index("idx_edinet_doc_submission_date")
        batch_op.drop_index("idx_edinet_doc_sec_code")
        batch_op.drop_index("idx_edinet_doc_doc_id")

    op.drop_table("edinet_document")
    # ### end Alembic commands ###
