"""feat(db): add tables for batch_execution_details and stock_master_updates.

Revision ID: 5eb81fa2fa7a
Revises: 892e1f109de2
Create Date: 2026-01-17 17:58:35.475244

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5eb81fa2fa7a"
down_revision: Union[str, Sequence[str], None] = "892e1f109de2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_master_updates",
        sa.Column("update_type", sa.String(length=20), nullable=False),
        sa.Column("total_stocks", sa.Integer(), nullable=False),
        sa.Column("added_stocks", sa.Integer(), nullable=False),
        sa.Column("updated_stocks", sa.Integer(), nullable=False),
        sa.Column("removed_stocks", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "batch_execution_details",
        sa.Column("batch_execution_id", sa.Integer(), nullable=False),
        sa.Column("interval", sa.String(length=20), nullable=True),
        sa.Column("total_stocks", sa.Integer(), nullable=False),
        sa.Column("processed_stocks", sa.Integer(), nullable=False),
        sa.Column("successful_stocks", sa.Integer(), nullable=False),
        sa.Column("failed_stocks", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_execution_id"], ["batch_executions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_batch_execution_details_batch_id",
        "batch_execution_details",
        ["batch_execution_id"],
        unique=False,
    )
    op.create_index(
        "idx_batch_execution_details_batch_interval",
        "batch_execution_details",
        ["batch_execution_id", "interval"],
        unique=False,
    )
    op.create_index(
        "idx_batch_execution_details_interval",
        "batch_execution_details",
        ["interval"],
        unique=False,
    )
    op.create_index(
        "idx_batch_execution_details_status",
        "batch_execution_details",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_batch_execution_details_status",
        table_name="batch_execution_details",
    )
    op.drop_index(
        "idx_batch_execution_details_interval",
        table_name="batch_execution_details",
    )
    op.drop_index(
        "idx_batch_execution_details_batch_interval",
        table_name="batch_execution_details",
    )
    op.drop_index(
        "idx_batch_execution_details_batch_id",
        table_name="batch_execution_details",
    )
    op.drop_table("batch_execution_details")
    op.drop_table("stock_master_updates")
    # ### end Alembic commands ###
