"""Add edinet_dividend_metrics table

Revision ID: 67bd98bae213
Revises:
Create Date: 2026-03-15 18:53:38.059460

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67bd98bae213"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_index("idx_account_email", ["email"], unique=False)

    op.create_table(
        "dividend_yield_monitoring",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("monitoring_date", sa.Date(), nullable=False),
        sa.Column("latest_dividend_amount", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("latest_stock_price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("dividend_yield", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("purchase_level", sa.String(length=20), nullable=True),
        sa.Column("screening_status", sa.String(length=20), nullable=True),
        sa.Column("screening_total_score", sa.Integer(), nullable=True),
        sa.Column("stock_price_source_date", sa.Date(), nullable=True),
        sa.Column("dividend_source_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "monitoring_date", name="uq_dividend_yield_monitoring"),
    )
    with op.batch_alter_table("dividend_yield_monitoring", schema=None) as batch_op:
        batch_op.create_index(
            "idx_dividend_yield_monitoring_date", ["monitoring_date"], unique=False
        )
        batch_op.create_index(
            "idx_dividend_yield_monitoring_purchase_level", ["purchase_level"], unique=False
        )
        batch_op.create_index(
            "idx_dividend_yield_monitoring_yield", ["dividend_yield"], unique=False
        )

    op.create_table(
        "edinet_document",
        sa.Column("doc_id", sa.String(length=50), nullable=False),
        sa.Column("sec_code", sa.String(length=10), nullable=False),
        sa.Column("submission_date", sa.Date(), nullable=False),
        sa.Column("report_type", sa.String(length=20), nullable=False),
        sa.Column("candidate_contexts", sa.String(length=50), nullable=True),
        sa.Column("candidate_keys", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_id"),
        sa.UniqueConstraint("doc_id", name="uq_edinet_doc_id"),
    )
    with op.batch_alter_table("edinet_document", schema=None) as batch_op:
        batch_op.create_index("idx_edinet_doc_doc_id", ["doc_id"], unique=True)
        batch_op.create_index("idx_edinet_doc_sec_code", ["sec_code"], unique=False)
        batch_op.create_index("idx_edinet_doc_submission_date", ["submission_date"], unique=False)

    op.create_table(
        "market_category_master",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("market_category_master", schema=None) as batch_op:
        batch_op.create_index("idx_market_category_code", ["code"], unique=False)

    op.create_table(
        "scale_master",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("scale_master", schema=None) as batch_op:
        batch_op.create_index("idx_scale_code", ["code"], unique=False)

    op.create_table(
        "screening_results",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("evaluation_year", sa.Integer(), nullable=False),
        sa.Column("fiscal_year_end", sa.Date(), nullable=True),
        sa.Column(
            "pass_required_conditions", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("total_score", sa.Integer(), nullable=True),
        sa.Column("score_dividend", sa.Integer(), nullable=True),
        sa.Column("score_eps", sa.Integer(), nullable=True),
        sa.Column("score_stability", sa.Integer(), nullable=True),
        sa.Column("score_profitability", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'not_eligible'"), nullable=False
        ),
        sa.Column("failed_conditions", sa.JSON(), nullable=True),
        sa.Column("screening_details", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "evaluation_year", name="uq_screening_results_symbol_year"),
    )
    with op.batch_alter_table("screening_results", schema=None) as batch_op:
        batch_op.create_index(
            "idx_screening_results_evaluation_year", ["evaluation_year"], unique=False
        )
        batch_op.create_index("idx_screening_results_status", ["status"], unique=False)
        batch_op.create_index("idx_screening_results_symbol", ["symbol"], unique=False)
        batch_op.create_index("idx_screening_results_total_score", ["total_score"], unique=False)

    op.create_table(
        "sector_17_master",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("sector_17_master", schema=None) as batch_op:
        batch_op.create_index("idx_sector_17_code", ["code"], unique=False)

    op.create_table(
        "sector_33_master",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("sector_33_master", schema=None) as batch_op:
        batch_op.create_index("idx_sector_33_code", ["code"], unique=False)

    op.create_table(
        "stock_code_mapping",
        sa.Column("stock_code", sa.String(length=10), nullable=False),
        sa.Column("sec_code", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sec_code"),
        sa.UniqueConstraint("stock_code", "sec_code", name="uq_stock_code_mapping"),
    )
    with op.batch_alter_table("stock_code_mapping", schema=None) as batch_op:
        batch_op.create_index("idx_stock_code_mapping_sec_code", ["sec_code"], unique=False)
        batch_op.create_index("idx_stock_code_mapping_stock_code", ["stock_code"], unique=False)

    op.create_table(
        "stock_master_updates",
        sa.Column("update_type", sa.String(length=20), nullable=False),
        sa.Column("total_stocks", sa.Integer(), nullable=False),
        sa.Column("added_stocks", sa.Integer(), nullable=False),
        sa.Column("updated_stocks", sa.Integer(), nullable=False),
        sa.Column("removed_stocks", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stock_split",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("ratio_from", sa.Integer(), nullable=True),
        sa.Column("ratio_to", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_split", schema=None) as batch_op:
        batch_op.create_index("idx_stock_split_code", ["code"], unique=False)
        batch_op.create_index("idx_stock_split_effective", ["effective_date"], unique=False)

    op.create_table(
        "account_portfolios",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("portfolio_name", sa.String(length=100), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("market_value", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("valuation_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("allocation", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("account_portfolios", schema=None) as batch_op:
        batch_op.create_index("idx_account_portfolios_account", ["account_id"], unique=False)
        batch_op.create_index("idx_account_portfolios_symbol", ["symbol"], unique=False)

    op.create_table(
        "account_transactions",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("account_transactions", schema=None) as batch_op:
        batch_op.create_index("idx_account_transactions_account", ["account_id"], unique=False)
        batch_op.create_index("idx_account_transactions_executed_at", ["executed_at"], unique=False)
        batch_op.create_index("idx_account_transactions_symbol", ["symbol"], unique=False)

    op.create_table(
        "dividend_yield_history",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "dividend",
            sa.Numeric(precision=20, scale=4),
            nullable=True,
            comment="年間配当金（COALESCE(dividend_adj, dividend_actual)）",
        ),
        sa.Column(
            "stock_price",
            sa.Numeric(precision=20, scale=4),
            nullable=True,
            comment="株価（COALESCE(adj_close, close)）",
        ),
        sa.Column(
            "dividend_yield",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="配当利回り = dividend / stock_price",
        ),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("edinet_document_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edinet_document_id"],
            ["edinet_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "date", name="uq_dividend_yield_history_symbol_date"),
    )
    with op.batch_alter_table("dividend_yield_history", schema=None) as batch_op:
        batch_op.create_index("idx_dividend_yield_history_date", ["date"], unique=False)
        batch_op.create_index(
            "idx_dividend_yield_history_edinet_document_id", ["edinet_document_id"], unique=False
        )
        batch_op.create_index(
            "idx_dividend_yield_history_fiscal_year", ["fiscal_year"], unique=False
        )
        batch_op.create_index(
            "idx_dividend_yield_history_symbol_date", ["symbol", "date"], unique=False
        )

    op.create_table(
        "edinet_balance_sheet",
        sa.Column("edinet_document_id", sa.Integer(), nullable=False),
        sa.Column("period_end_date", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("total_assets", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("net_assets", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("shareholders_equity", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("bps", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("equity_ratio", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("is_consolidated", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edinet_document_id"],
            ["edinet_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "edinet_document_id", "period_end_date", name="uq_edinet_bs_doc_period"
        ),
    )
    with op.batch_alter_table("edinet_balance_sheet", schema=None) as batch_op:
        batch_op.create_index("idx_edinet_bs_document_id", ["edinet_document_id"], unique=False)
        batch_op.create_index("idx_edinet_bs_period_end", ["period_end_date"], unique=False)

    op.create_table(
        "edinet_cash_flow_statement",
        sa.Column("edinet_document_id", sa.Integer(), nullable=False),
        sa.Column("period_end_date", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column(
            "operating_cf",
            sa.Numeric(precision=20, scale=2),
            nullable=True,
            comment="営業キャッシュフロー（百万円）",
        ),
        sa.Column("is_consolidated", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edinet_document_id"],
            ["edinet_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "edinet_document_id", "period_end_date", name="uq_edinet_cfs_doc_period"
        ),
    )
    with op.batch_alter_table("edinet_cash_flow_statement", schema=None) as batch_op:
        batch_op.create_index("idx_edinet_cfs_document_id", ["edinet_document_id"], unique=False)
        batch_op.create_index("idx_edinet_cfs_period_end", ["period_end_date"], unique=False)

    op.create_table(
        "edinet_dividend_metrics",
        sa.Column("edinet_document_id", sa.Integer(), nullable=False),
        sa.Column("period_end_date", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("dividend_actual", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("eps", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column("payout_ratio", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("is_consolidated", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edinet_document_id"],
            ["edinet_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "edinet_document_id", "period_end_date", name="uq_edinet_dm_doc_period"
        ),
    )
    with op.batch_alter_table("edinet_dividend_metrics", schema=None) as batch_op:
        batch_op.create_index("idx_edinet_dm_document_id", ["edinet_document_id"], unique=False)
        batch_op.create_index("idx_edinet_dm_period_end", ["period_end_date"], unique=False)

    op.create_table(
        "edinet_profit_and_loss",
        sa.Column("edinet_document_id", sa.Integer(), nullable=False),
        sa.Column("period_end_date", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("net_sales", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("operating_income", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("eps", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("is_consolidated", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edinet_document_id"],
            ["edinet_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "edinet_document_id", "period_end_date", name="uq_edinet_pl_doc_period"
        ),
    )
    with op.batch_alter_table("edinet_profit_and_loss", schema=None) as batch_op:
        batch_op.create_index("idx_edinet_pl_document_id", ["edinet_document_id"], unique=False)
        batch_op.create_index("idx_edinet_pl_period_end", ["period_end_date"], unique=False)

    op.create_table(
        "edinet_stock_dividend",
        sa.Column("edinet_document_id", sa.Integer(), nullable=False),
        sa.Column("period_end_date", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column(
            "dividend_actual",
            sa.Numeric(precision=20, scale=2),
            nullable=True,
            comment="年間配当金（百万円または円など、ソースに依存）",
        ),
        sa.Column(
            "dividend_adj",
            sa.Numeric(precision=20, scale=2),
            nullable=True,
            comment="調整後年間配当金（百万円または円など、ソースに依存）",
        ),
        sa.Column("is_consolidated", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edinet_document_id"],
            ["edinet_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "edinet_document_id", "period_end_date", name="uq_edinet_sd_doc_period"
        ),
    )
    with op.batch_alter_table("edinet_stock_dividend", schema=None) as batch_op:
        batch_op.create_index("idx_edinet_sd_document_id", ["edinet_document_id"], unique=False)
        batch_op.create_index("idx_edinet_sd_period_end", ["period_end_date"], unique=False)

    op.create_table(
        "stock_master",
        sa.Column("stock_code", sa.String(length=10), nullable=False),
        sa.Column("stock_name", sa.String(length=100), nullable=False),
        sa.Column("market_category_id", sa.Integer(), nullable=True),
        sa.Column("sector_33_id", sa.Integer(), nullable=True),
        sa.Column("sector_17_id", sa.Integer(), nullable=True),
        sa.Column("scale_id", sa.Integer(), nullable=True),
        sa.Column("data_date", sa.String(length=8), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["market_category_id"],
            ["market_category_master.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["scale_master.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sector_17_id"],
            ["sector_17_master.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sector_33_id"],
            ["sector_33_master.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stock_code"),
    )
    with op.batch_alter_table("stock_master", schema=None) as batch_op:
        batch_op.create_index("idx_stock_master_active", ["is_active"], unique=False)
        batch_op.create_index("idx_stock_master_code", ["stock_code"], unique=False)
        batch_op.create_index(
            "idx_stock_master_market_category_id", ["market_category_id"], unique=False
        )
        batch_op.create_index("idx_stock_master_sector_33_id", ["sector_33_id"], unique=False)

    op.create_table(
        "stocks_15m",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_15m_symbol_timestamp"),
    )
    with op.batch_alter_table("stocks_15m", schema=None) as batch_op:
        batch_op.create_index("idx_stocks_15m_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "stocks_1d",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1d_symbol_timestamp"),
    )
    with op.batch_alter_table("stocks_1d", schema=None) as batch_op:
        batch_op.create_index("idx_stocks_1d_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "stocks_1h",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1h_symbol_timestamp"),
    )
    with op.batch_alter_table("stocks_1h", schema=None) as batch_op:
        batch_op.create_index("idx_stocks_1h_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "stocks_1m",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1m_symbol_timestamp"),
    )
    with op.batch_alter_table("stocks_1m", schema=None) as batch_op:
        batch_op.create_index("idx_stocks_1m_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "stocks_1mo",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1mo_symbol_timestamp"),
    )
    with op.batch_alter_table("stocks_1mo", schema=None) as batch_op:
        batch_op.create_index("idx_stocks_1mo_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "stocks_1wk",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_1wk_symbol_timestamp"),
    )
    with op.batch_alter_table("stocks_1wk", schema=None) as batch_op:
        batch_op.create_index("idx_stocks_1wk_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "stocks_30m",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_30m_symbol_timestamp"),
    )
    with op.batch_alter_table("stocks_30m", schema=None) as batch_op:
        batch_op.create_index("idx_stocks_30m_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "stocks_5m",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stock_master.stock_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", name="uix_stocks_5m_symbol_timestamp"),
    )
    with op.batch_alter_table("stocks_5m", schema=None) as batch_op:
        batch_op.create_index("idx_stocks_5m_timestamp", ["timestamp"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stocks_5m", schema=None) as batch_op:
        batch_op.drop_index("idx_stocks_5m_timestamp")

    op.drop_table("stocks_5m")
    with op.batch_alter_table("stocks_30m", schema=None) as batch_op:
        batch_op.drop_index("idx_stocks_30m_timestamp")

    op.drop_table("stocks_30m")
    with op.batch_alter_table("stocks_1wk", schema=None) as batch_op:
        batch_op.drop_index("idx_stocks_1wk_timestamp")

    op.drop_table("stocks_1wk")
    with op.batch_alter_table("stocks_1mo", schema=None) as batch_op:
        batch_op.drop_index("idx_stocks_1mo_timestamp")

    op.drop_table("stocks_1mo")
    with op.batch_alter_table("stocks_1m", schema=None) as batch_op:
        batch_op.drop_index("idx_stocks_1m_timestamp")

    op.drop_table("stocks_1m")
    with op.batch_alter_table("stocks_1h", schema=None) as batch_op:
        batch_op.drop_index("idx_stocks_1h_timestamp")

    op.drop_table("stocks_1h")
    with op.batch_alter_table("stocks_1d", schema=None) as batch_op:
        batch_op.drop_index("idx_stocks_1d_timestamp")

    op.drop_table("stocks_1d")
    with op.batch_alter_table("stocks_15m", schema=None) as batch_op:
        batch_op.drop_index("idx_stocks_15m_timestamp")

    op.drop_table("stocks_15m")
    with op.batch_alter_table("stock_master", schema=None) as batch_op:
        batch_op.drop_index("idx_stock_master_sector_33_id")
        batch_op.drop_index("idx_stock_master_market_category_id")
        batch_op.drop_index("idx_stock_master_code")
        batch_op.drop_index("idx_stock_master_active")

    op.drop_table("stock_master")
    with op.batch_alter_table("edinet_stock_dividend", schema=None) as batch_op:
        batch_op.drop_index("idx_edinet_sd_period_end")
        batch_op.drop_index("idx_edinet_sd_document_id")

    op.drop_table("edinet_stock_dividend")
    with op.batch_alter_table("edinet_profit_and_loss", schema=None) as batch_op:
        batch_op.drop_index("idx_edinet_pl_period_end")
        batch_op.drop_index("idx_edinet_pl_document_id")

    op.drop_table("edinet_profit_and_loss")
    with op.batch_alter_table("edinet_dividend_metrics", schema=None) as batch_op:
        batch_op.drop_index("idx_edinet_dm_period_end")
        batch_op.drop_index("idx_edinet_dm_document_id")

    op.drop_table("edinet_dividend_metrics")
    with op.batch_alter_table("edinet_cash_flow_statement", schema=None) as batch_op:
        batch_op.drop_index("idx_edinet_cfs_period_end")
        batch_op.drop_index("idx_edinet_cfs_document_id")

    op.drop_table("edinet_cash_flow_statement")
    with op.batch_alter_table("edinet_balance_sheet", schema=None) as batch_op:
        batch_op.drop_index("idx_edinet_bs_period_end")
        batch_op.drop_index("idx_edinet_bs_document_id")

    op.drop_table("edinet_balance_sheet")
    with op.batch_alter_table("dividend_yield_history", schema=None) as batch_op:
        batch_op.drop_index("idx_dividend_yield_history_symbol_date")
        batch_op.drop_index("idx_dividend_yield_history_fiscal_year")
        batch_op.drop_index("idx_dividend_yield_history_edinet_document_id")
        batch_op.drop_index("idx_dividend_yield_history_date")

    op.drop_table("dividend_yield_history")
    with op.batch_alter_table("account_transactions", schema=None) as batch_op:
        batch_op.drop_index("idx_account_transactions_symbol")
        batch_op.drop_index("idx_account_transactions_executed_at")
        batch_op.drop_index("idx_account_transactions_account")

    op.drop_table("account_transactions")
    with op.batch_alter_table("account_portfolios", schema=None) as batch_op:
        batch_op.drop_index("idx_account_portfolios_symbol")
        batch_op.drop_index("idx_account_portfolios_account")

    op.drop_table("account_portfolios")
    with op.batch_alter_table("stock_split", schema=None) as batch_op:
        batch_op.drop_index("idx_stock_split_effective")
        batch_op.drop_index("idx_stock_split_code")

    op.drop_table("stock_split")
    op.drop_table("stock_master_updates")
    with op.batch_alter_table("stock_code_mapping", schema=None) as batch_op:
        batch_op.drop_index("idx_stock_code_mapping_stock_code")
        batch_op.drop_index("idx_stock_code_mapping_sec_code")

    op.drop_table("stock_code_mapping")
    with op.batch_alter_table("sector_33_master", schema=None) as batch_op:
        batch_op.drop_index("idx_sector_33_code")

    op.drop_table("sector_33_master")
    with op.batch_alter_table("sector_17_master", schema=None) as batch_op:
        batch_op.drop_index("idx_sector_17_code")

    op.drop_table("sector_17_master")
    with op.batch_alter_table("screening_results", schema=None) as batch_op:
        batch_op.drop_index("idx_screening_results_total_score")
        batch_op.drop_index("idx_screening_results_symbol")
        batch_op.drop_index("idx_screening_results_status")
        batch_op.drop_index("idx_screening_results_evaluation_year")

    op.drop_table("screening_results")
    with op.batch_alter_table("scale_master", schema=None) as batch_op:
        batch_op.drop_index("idx_scale_code")

    op.drop_table("scale_master")
    with op.batch_alter_table("market_category_master", schema=None) as batch_op:
        batch_op.drop_index("idx_market_category_code")

    op.drop_table("market_category_master")
    with op.batch_alter_table("edinet_document", schema=None) as batch_op:
        batch_op.drop_index("idx_edinet_doc_submission_date")
        batch_op.drop_index("idx_edinet_doc_sec_code")
        batch_op.drop_index("idx_edinet_doc_doc_id")

    op.drop_table("edinet_document")
    with op.batch_alter_table("dividend_yield_monitoring", schema=None) as batch_op:
        batch_op.drop_index("idx_dividend_yield_monitoring_yield")
        batch_op.drop_index("idx_dividend_yield_monitoring_purchase_level")
        batch_op.drop_index("idx_dividend_yield_monitoring_date")

    op.drop_table("dividend_yield_monitoring")
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_index("idx_account_email")

    op.drop_table("account")
    # ### end Alembic commands ###
