"""add accounts/account_transactions/account_portfolios models

Revision ID: 892e1f109de2
Revises: a34daef60fc9
Create Date: 2026-01-16 08:35:08.186864

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "892e1f109de2"
down_revision: Union[str, Sequence[str], None] = "a34daef60fc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_account_email", "account", ["email"], unique=False)
    op.create_table(
        "account_portfolios",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("portfolio_name", sa.String(length=100), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "avg_price", sa.Numeric(precision=18, scale=4), nullable=True
        ),
        sa.Column(
            "market_value", sa.Numeric(precision=20, scale=2), nullable=True
        ),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("valuation_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "allocation", sa.Numeric(precision=6, scale=4), nullable=True
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_account_portfolios_account",
        "account_portfolios",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        "idx_account_portfolios_symbol",
        "account_portfolios",
        ["symbol"],
        unique=False,
    )
    op.create_table(
        "account_transactions",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_account_transactions_account",
        "account_transactions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        "idx_account_transactions_executed_at",
        "account_transactions",
        ["executed_at"],
        unique=False,
    )
    op.create_index(
        "idx_account_transactions_symbol",
        "account_transactions",
        ["symbol"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_account_transactions_symbol", table_name="account_transactions"
    )
    op.drop_index(
        "idx_account_transactions_executed_at",
        table_name="account_transactions",
    )
    op.drop_index(
        "idx_account_transactions_account", table_name="account_transactions"
    )
    op.drop_table("account_transactions")
    op.drop_index(
        "idx_account_portfolios_symbol", table_name="account_portfolios"
    )
    op.drop_index(
        "idx_account_portfolios_account", table_name="account_portfolios"
    )
    op.drop_table("account_portfolios")
    op.drop_index("idx_account_email", table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
