"""add stock_code_mapping table for JPX-EDINET code mapping

Revision ID: 899d483500c7
Revises: 46e4c7c13389
Create Date: 2026-02-26 18:53:47.634478

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "899d483500c7"
down_revision: Union[str, Sequence[str], None] = "46e4c7c13389"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_code_mapping",
        sa.Column("stock_code", sa.String(length=10), nullable=False),
        sa.Column("sec_code", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sec_code"),
        sa.UniqueConstraint("stock_code", "sec_code", name="uq_stock_code_mapping"),
    )
    with op.batch_alter_table("stock_code_mapping", schema=None) as batch_op:
        batch_op.create_index("idx_stock_code_mapping_sec_code", ["sec_code"], unique=False)
        batch_op.create_index("idx_stock_code_mapping_stock_code", ["stock_code"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_code_mapping", schema=None) as batch_op:
        batch_op.drop_index("idx_stock_code_mapping_stock_code")
        batch_op.drop_index("idx_stock_code_mapping_sec_code")

    op.drop_table("stock_code_mapping")
    # ### end Alembic commands ###
