"""add new models.

Revision ID: a34daef60fc9
Revises: 4e581533f2e4
Create Date: 2026-01-15 23:20:37.286284

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a34daef60fc9"
down_revision: Union[str, Sequence[str], None] = "4e581533f2e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
