"""add_nikkei225_components_table

Revision ID: b05c0de5acc0
Revises: 0d155fb7e046
Create Date: 2026-04-18 12:08:34.696282

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b05c0de5acc0"
down_revision: Union[str, Sequence[str], None] = "0d155fb7e046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nikkei225_components",
        sa.Column("stock_code", sa.String(length=4), nullable=False),
        sa.Column("price_adjustment_factor", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stock_code"],
            ["stock_master.stock_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stock_code", "effective_date", name="uq_nikkei225_code_date"),
    )
    with op.batch_alter_table("nikkei225_components", schema=None) as batch_op:
        batch_op.create_index("idx_nikkei225_effective_date", ["effective_date"], unique=False)
        batch_op.create_index("idx_nikkei225_stock_code", ["stock_code"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nikkei225_components", schema=None) as batch_op:
        batch_op.drop_index("idx_nikkei225_stock_code")
        batch_op.drop_index("idx_nikkei225_effective_date")

    op.drop_table("nikkei225_components")
    # ### end Alembic commands ###
