"""create edinet_profit_and_loss model.

Revision ID: db11330dca45
Revises: dffe4583e257
Create Date: 2026-02-13 19:41:11.192693

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db11330dca45"
down_revision: Union[str, Sequence[str], None] = "dffe4583e257"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("edinet_cash_flow_statement", schema=None) as batch_op:
        try:
            batch_op.drop_index(batch_op.f("idx_edinet_cfs_doc_id"))
        except ValueError:
            pass
        try:
            batch_op.drop_index(batch_op.f("idx_edinet_cfs_period_end"))
        except ValueError:
            pass
        try:
            batch_op.drop_index(batch_op.f("idx_edinet_cfs_sec_code"))
        except ValueError:
            pass
        try:
            batch_op.drop_index(batch_op.f("idx_edinet_cfs_sec_period"))
        except ValueError:
            pass

    op.drop_table("edinet_cash_flow_statement")
    with op.batch_alter_table("edinet_stock_dividend", schema=None) as batch_op:
        try:
            batch_op.drop_index(batch_op.f("idx_edinet_sd_doc_id"))
        except ValueError:
            pass
        try:
            batch_op.drop_index(batch_op.f("idx_edinet_sd_period_end"))
        except ValueError:
            pass
        try:
            batch_op.drop_index(batch_op.f("idx_edinet_sd_sec_code"))
        except ValueError:
            pass
        try:
            batch_op.drop_index(batch_op.f("idx_edinet_sd_sec_period"))
        except ValueError:
            pass

    op.drop_table("edinet_stock_dividend")
    with op.batch_alter_table("edinet_profit_and_loss", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("net_sales", sa.Numeric(precision=20, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("operating_income", sa.Numeric(precision=20, scale=2), nullable=True)
        )
        # Drop index only if it exists to avoid batch flush error on SQLite.
        # Using SQLAlchemy inspector to check existing indexes before registering drop.
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        existing_indexes = {idx["name"] for idx in inspector.get_indexes("edinet_profit_and_loss")}
        idx_name = batch_op.f("idx_edinet_pl_sec_period")
        if idx_name in existing_indexes or "idx_edinet_pl_sec_period" in existing_indexes:
            batch_op.drop_index(idx_name)
        batch_op.drop_column("filer_name")
        batch_op.drop_column("operating_profit")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("edinet_profit_and_loss", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("operating_profit", sa.NUMERIC(precision=20, scale=2), nullable=True)
        )
        batch_op.add_column(sa.Column("filer_name", sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(
            batch_op.f("idx_edinet_pl_sec_period"), ["sec_code", "period_end_date"], unique=False
        )
        batch_op.drop_column("operating_income")
        batch_op.drop_column("net_sales")

    op.create_table(
        "edinet_stock_dividend",
        sa.Column("doc_id", sa.VARCHAR(length=50), nullable=False),
        sa.Column("sec_code", sa.VARCHAR(length=10), nullable=False),
        sa.Column("submission_date", sa.DATE(), nullable=False),
        sa.Column("period_end_date", sa.DATE(), nullable=False),
        sa.Column("fiscal_year", sa.INTEGER(), nullable=True),
        sa.Column("report_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("dividend_actual", sa.NUMERIC(precision=20, scale=2), nullable=True),
        sa.Column("candidate_contexts", sa.VARCHAR(length=50), nullable=True),
        sa.Column("candidate_keys", sa.VARCHAR(length=50), nullable=True),
        sa.Column("is_consolidated", sa.BOOLEAN(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sec_code", "period_end_date", name=op.f("uq_edinet_sd_sec_period")),
    )
    with op.batch_alter_table("edinet_stock_dividend", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_edinet_sd_sec_period"), ["sec_code", "period_end_date"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_edinet_sd_sec_code"), ["sec_code"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_edinet_sd_period_end"), ["period_end_date"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_edinet_sd_doc_id"), ["doc_id"], unique=False)

    op.create_table(
        "edinet_cash_flow_statement",
        sa.Column("doc_id", sa.VARCHAR(length=50), nullable=False),
        sa.Column("sec_code", sa.VARCHAR(length=10), nullable=False),
        sa.Column("submission_date", sa.DATE(), nullable=False),
        sa.Column("period_end_date", sa.DATE(), nullable=False),
        sa.Column("fiscal_year", sa.INTEGER(), nullable=True),
        sa.Column("report_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("operating_cf", sa.NUMERIC(precision=20, scale=2), nullable=True),
        sa.Column("candidate_contexts", sa.VARCHAR(length=50), nullable=True),
        sa.Column("candidate_keys", sa.VARCHAR(length=50), nullable=True),
        sa.Column("is_consolidated", sa.BOOLEAN(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sec_code", "period_end_date", name=op.f("uq_edinet_cfs_sec_period")),
    )
    with op.batch_alter_table("edinet_cash_flow_statement", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_edinet_cfs_sec_period"), ["sec_code", "period_end_date"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_edinet_cfs_sec_code"), ["sec_code"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_edinet_cfs_period_end"), ["period_end_date"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_edinet_cfs_doc_id"), ["doc_id"], unique=False)

    # ### end Alembic commands ###
