"""create missing models from metadata.

Revision ID: f1a2b3c4d5e6
Revises: d5a1c2b3e4f6
Create Date: 2026-02-09 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1a2b3c4d5e6"
down_revision: Union[str, Sequence[str], None] = "d5a1c2b3e4f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create any tables present in the SQLAlchemy metadata but missing in the DB.

    This uses `Base.metadata.create_all()` which will only create tables
    that do not exist yet. It's a pragmatic way to bring the SQLite DB into
    parity when some autogenerated migrations were not committed.
    """
    # Import inside function to avoid import-time side-effects for Alembic
    from app.models import Base

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    """No-op downgrade: dropping all tables automatically would be unsafe.

    If you prefer explicit downgrades, replace this with targeted drops.
    """
    pass
